Customer.create!({"name" => "Jack Black", "phone" => "2042942035", "email" => "", "notes" => "first"})
Customer.create!({"name" => "Matt Black", "phone" => "4310543259", "email" => "", "notes" => "disc 10%"})
Customer.create!({"name" => "Frank Doe", "phone" => "2049523507", "email" => "fdoe@example.com", "notes" => "Lives in Alberta"})
Customer.create!({"name" => "Mary Doe", "phone" => "4310520546", "email" => "", "notes" => ""})
Customer.create!({"name" => "Jhon Jhonson", "phone" => "2059856520", "email" => "jhonj@example.com", "notes" => ""})
